### ISSUE TITLE
Handle wrong user input

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#1]
Wenn parameter nicht vollständig angegeben, dann fehler zurückgeben.

Ignoriere dabei
- alle mit `_openml*` fullName bzw. `openml.*`
- Parameter die alle die gleichen Einträge haben für den entsprechenden Algo

**Comment by mboecker** [comment]
TODO:
- [ ] Add function to return named list with needed parameters and proper bounds
- [ ] Re-write /parameters to use said function
- [ ] Add check in /lookup to use said function

**Comment by jakob-r** [comment]
`ranger` got new parameter replace = TRUE/FALSE. Default is TRUE. We have observations where no value for that param is in the database. Probably TRUE should be the case here.
Ask @PhilippPro?

**Comment by jakob-r** [comment]
Maybe check for other learners as well.

**Comment by PhilippPro** [comment]
Yes. If the parameter is not given/saved by OpenML, the default was used. 

In this case (replace parameter) the default is TRUE.

**Comment by jakob-r** [comment]
But it is strange that this default is not saved. Is that the case with all defaults?

**Comment by PhilippPro** [comment]
Yes.

**Comment by jakob-r** [comment]
But the default is only encoded in the mlr learner definition and not in the `botSetLearnerParamPairs.R`? That is a bit unfortunate because it's hard to track the changes there. Although - of course - there should not be so many (none at all hopefully)

**Comment by PhilippPro** [comment]
Yes, the defaults are defined by mlr.

**Comment by jakob-r** [comment]
So you sample from the values TRUE and FALSE. And get e.g. TRUE. Then you pass this value further to some function and this function checks if the value is equal to the default and then decides to drop it? Is that a "feature" of OML or the Bot? Where does it happen exactly? What is the motivation behind it?

**Comment by PhilippPro** [comment]
I think for the exact details you better ask Bernd or Giuseppe in the OpenML-r github repo.

**Comment by PhilippPro** [comment]
No. I just used the standard form of submitting runs (10-fold CV) to OpenML.
