### ISSUE TITLE
Cleanup of parameter_ranges generation

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#10]
- Use the package instead of copying the source
- clean up the re-formatting code

**Comment by mboecker** [comment]
Done in b322517884c64d20f294c7bec24d27184eafc6f8.
The package didn't compile with devtools::install_github because of something wrong in the documentation:

```
Error : /tmp/Rtmp0gbara/devtools13142d756182/ja-thomas-OMLbots-02f64a4/man/addDefaultValues.Rd: Sections \title, and \name must exist and be unique in Rd files
ERROR: installing Rd objects failed for package ‘OMLbot2’
```

Therefore I instead source(..)'d the right files directly from the omlbot-repo to keep them up to date that way (see attached commit). Are you okay with that?

**Comment by jakob-r** [comment]
Okay for the moment.
