### ISSUE TITLE
Regarding algorithm IDs like ranger(15)

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#11]
- [ ] wait until Jakob has an answer
- [ ] maybe change API from algo_id to algo_name

**Comment by jakob-r** [comment]
Maybe we can have both. Algo by id and algo by name? The latter then uses all ids that fits the name? More important is the last one.
The new ids are introduced when a learner gets a new version. This usually should not affect the outcome.

**Comment by mboecker** [comment]
This should be working by now.

**Comment by mboecker** [comment]
If the algo parameter is non-numeric, it just assumes its the algorithm name.
