### ISSUE TITLE
Fix parameter_ranges (NULL bounds)

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#13]
Find out, why some parameter bounds in parameter_ranges are NULL.
Probably factors. Find some work-around.

**Comment by jakob-r** [comment]
just accept that parameter_ranges can be NULL. factors should have parameter_values(?). They are mutually exclusive.

**Comment by mboecker** [comment]
Yes, thats exactly what I was thinking.

**Comment by mboecker** [comment]
By using your paramToJSONList, this is done (in c92be12a8912f994cbe46f0032aefc483d37856b).
