### ISSUE TITLE
Why is there a NA in the Result

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#28]
```r
library(devtools)
load_all()
startOmlTuneServer()

lrn.str = "classif.kknn"
task.id = 3

of = makeOmlBenchFunction(lrn.str, task.id)
par.set = getParamSet(of)
of(list(alpha = 0.9591837, lambda = -7.959184))
```
```
[1] "NA"
attr(,"extras")
attr(,"extras")$setup_id
[1] 2584374

attr(,"extras")$distance
[1] 0.0268

attr(,"extras")$impl_id
[1] 6766

attr(,"extras")$params
attr(,"extras")$params$alpha
[1] "0.944807519903407"

attr(,"extras")$params$s
[1] "0.01"

attr(,"extras")$params$lambda
[1] "0.00395580522083157"

attr(,"extras")$params$openml.seed
[1] "1"

attr(,"extras")$params$openml.kind
[1] "Mersenne-Twister"

attr(,"extras")$params$openml.normal.kind
[1] "Inversion"
```
Why does it return an NA value?
This is especially strange as the setup id 2584374 does not seem to fit:
https://www.openml.org/r/2584374
For other results the setup_id fits the run

**Comment by mboecker** [comment]
Weird. But since you're using "classif.kknn" with wrong parameters (alpha, lambda) it's clear that the result is incorrect.

Interestingly, the wrong parameter names are not caught.

**Comment by jakob-r** [comment]
I guess it was copy paste mistake. Originally it should have been `classif.glmnet`. But now with the scaling the example is outdated. Will open another issue if it reappears.
