### ISSUE TITLE
API Call that returns needed Params

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#3]
Also somewhere we need the meta information what the concrete possible ranges are.

**Comment by jakob-r** [comment]
Can be found here
https://github.com/ja-thomas/OMLbots/blob/02f64a48ab45215700ab3c1ef0566c9fc3ac5a74/R/botSetLearnerParamPairs.R#L29

**Comment by mboecker** [comment]
Done in 3d1d90f4ff8384eb7208e226bd6575d9e311581e
If the algorithm is not found in the source link from your second comment, the script returns the minimum and maximum from the database as upper and lower limits.
