### ISSUE TITLE
Add run_ids to the API output

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#30]
Can it be that we have entries that are not from user 2702 (openML bot) in the small example dataset?

I found run 29090 which belongs to flow 5526 which belongs to user 1478 (Janek)
https://www.openml.org/f/5890

**Comment by mboecker** [comment]
I don't think the API outputs the run_id at all, but only the setup_id.
setup_id 29090 belongs to our bot:
```+---------+-------+----------+
| rid     | setup | uploader |
+---------+-------+----------+
| 8452783 | 29090 |     2702 |
| 8452874 | 29090 |     2702 |
| 8452884 | 29090 |     2702 |
| 8452959 | 29090 |     2702 |
| 8453001 | 29090 |     2702 |
| 8453751 | 29090 |     2702 |
| 8453842 | 29090 |     2702 |
| 8453849 | 29090 |     2702 |
| 8454007 | 29090 |     2702 |
+---------+-------+----------+
```

**Comment by jakob-r** [comment]
ah well. I always get confused because the naming is different between the database and the openml interface. 
* Can you write down the translation somewhere in this repository?
* Can we return the run id?

**Comment by mboecker** [comment]
1. I don't think the setup concept is on the openml website at all. It seems that a flow is basically a setup, but associated to a given task. A setup is a specific set of parameter values, but not associated to a specific task. It's the settings of the algorithm only.
2. The algorithm works on setups and there can be multiple runs for the given task and a specific setup. Therefore, we currently average over the found runs. We could return all these run ids, if thats useful.

**Comment by mboecker** [comment]
- Warning, if not all values are equal
- latest rid ausgeben
