### ISSUE TITLE
Does the nearest neighbour really work?

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#33]
I don't have the impression:

Check this query:
```r
> x
$num.trees
[1] 1166

$replace
[1] TRUE

$sample.fraction
[1] 0.2772524

$mtry
[1] 0.234462

$respect.unordered.factors
[1] FALSE

$min.node.size
[1] 0.09384192
```
```
http://localhost:8746/?algo=classif.ranger&task=3&parameters={%22num.trees%22:[1166],%22replace%22:[true],%22sample.fraction%22:[0.2773],%22mtry%22:[0.2345],%22respect.unordered.factors%22:[false],%22min.node.size%22:[0.0938]}
```

and the response
```json
[{"setup_ids":6471633,"distances":2.482,"impl_id":6794,"performance":0.9994,"num.trees":1168,"mtry":10,"min.node.size":3,"sample.fraction":0.6777,"num.threads":1,"verbose":false}]
```

**Comment by jakob-r** [comment]
Maybe just the result is confusing.
* Where is `replace` gone?
* `sample fraction` seems like a too big distance. Does `num.trees` dominate? Normalization works?
* Where is `respect.unordered.factors` gone?

**Comment by jakob-r** [comment]
1) Let's return the complete setting.
2) Is there something written about the normalization?

**Comment by mboecker** [comment]
1. This should be done.
2. Since KNN is useless without normalization, I thought it's present in the impl. It is not stated anywhere though. Can we use `scale` for this?

> scale is generic function whose default method centers and/or scales the columns of a numeric matrix.

**Comment by jakob-r** [comment]
I implemented a scaling but your last change introduced a bug. I will open new Issue
