### ISSUE TITLE
Can we improve the database handling?

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#34]
After some superficial research I asked myself if we are using the smartest way possible to manage the database stuff. After all we are definitely not the first ones that use a database in a docker container:

* https://stackoverflow.com/questions/43880026/import-data-sql-mysql-docker-container

I also like the possibility to externally call something like this
```
gzip -cd mysqldata/database.sql.gz | docker exec -i $user-omlbotlookup /usr/bin/mysql openml
```
because this is blocking the terminal until the execution is finished and it might helt to see why travis fails.

**Comment by jakob-r** [comment]
I tried another version to start the container so we can see what's happening...
Somehow mysql fails to start.

https://travis-ci.org/mboecker/lookup-server/builds/369139884#L4653

**Comment by mboecker** [comment]
It's possible, that the data import is just too slow for travis.

https://travis-ci.org/mboecker/lookup-server/builds/369139884#L4731

It seems like it's just running the test script we wrote. When starting up the container takes too long, it terminates the build. We could use a much smaller database file for travis?

**Comment by jakob-r** [comment]
This is because I set the timeout in the R package to 10mins. What happens behind is that the docker container is tried to start but fails silently so that we just see the timeout.

**Comment by mboecker** [comment]
We could start the mysql server in the container, call "mysql" from externally like you suggested and then start using the API. It's just not a good idea to start using the server before the database is imported.

**Comment by mboecker** [comment]
With the newest commit, one can

1. start the server using run-fg.sh or start-fg.sh
2. (this will start the mysql database and the API)
3. use either `cat data.sql | ./import_data.sh` or `gzip -cd data.sql.gz | ./import_data.sh` to import whatever .sql file he wants into the server/docker container.
4. start using the API.

We can hide this process in the package easily by calling these commands for the user.
This should solve this issue.

**Comment by mboecker** [comment]
Closed?

**Comment by jakob-r** [comment]
Yes
