### ISSUE TITLE
"R Session terminated" because of dfRowToList

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#37]
When I try to run the API, my R session terminates.
It is caused by this line:

https://github.com/mboecker/lookup-server/blob/master/docker/omlbotlookup/rest_api.R#L40

Is this the same bug as #36 ?

**Comment by mboecker** [comment]
I'm trying `rest_estimate_performance(3, "classif.ranger",'{"mtry":5}')`, but since this doesn't appear while trying #38, it could be caused by using a single parameter.

**Comment by jakob-r** [comment]
Can you give an example API call that produces this error?
It does not happen for me at the moment.
