### ISSUE TITLE
NA result for "classif.glmnet"

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#38]
Now with working example:
```
http://localhost:8746/?algo=classif.glmnet&task=3&parameters={%22alpha%22:[0.9473684],%22lambda%22:[-7.894737]}
```

```json
[{"setup_ids":2584374,"distances":0.0051,"impl_id":6766,"performance":"NA","alpha":0.9448,"s":0.01,"lambda":0.004}]
```

**Comment by jakob-r** [comment]
We have to delete Runs without evaluations somehow so that

**Comment by mboecker** [comment]
> We have to delete Runs without evaluations somehow so that they are not found as nearest neighbours.

I will do so with the new mysql reduce script.
