### ISSUE TITLE
API List all algorithms for given Task

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#4]

**Comment by mboecker** [comment]
Done in 9a5c8c83cb3b1721f6d6a4b6bf15e3b6452001f5
The API call is /algos?task=<task_id>, which will return a list of algo_ids.

**Comment by mboecker** [comment]
In 3115ffbbd4cc1703ff930d69331bdea0d1d56a73 I added the algorithm names, so one can choose an algorithm based on name.
