### ISSUE TITLE
Riddle solved? missing values due to Runs with tag: defaultRun

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#42]
After a hangout with Bernd, we might have a simple answer to all the missing values discussion.

1. Some runs are uploaded with the tag: defaultRun, these runs don't have parameters set and we should be able to ignore them.
2. Check if, after removing runs with the tag defaultRun, we have missing Values
3. Check additionally, if for kknn the default value of k = 1 is present in the remaining runs or in other words if all values of k between 1 and 30 are present. (Alternatively check num.trees = 500 for ranger)

**Comment by mboecker** [comment]
1 + 2) Because [the tag defaultRun is only set on xgboost](https://www.openml.org/search?q=tags.tag%3AdefaultRun&type=run), this cant be our only problem.

**Comment by jakob-r** [comment]
Ok, thats unfortunate... Can you link to a run where we supposedly don't have parameters set. Then @berndbischl, @giuseppec or @PhilippPro can maybe find out what's happening.
