### ISSUE TITLE
Start ignoring missing values

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#47]

**Comment by jakob-r** [comment]
I guess `complete.cases` might not be the best solution here. We have to check carefully.

Are we sure the table does only consist of columns that we really need to be not NA?

For some parameter settings NA is actually a valid value.
For instance: `classif.svm`. Here degree will be NA if `kernel != "polynomial"`

**Comment by mboecker** [comment]
You're right but then the user should not supply `degree` and then we won't request it from the db.

**Comment by jakob-r** [comment]
Then I suppose we have to make sure to drop NAs from the request.
