### ISSUE TITLE
runs without evaluation measures

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#49]
There are runs without any evaluation measure, for example https://www.openml.org/r/8688231
I'm currently counting how many runs are affected.

**Comment by mboecker** [comment]
OK funny story, if I load the reduced databases, I don't find any runs in the database that are missing the accuracy.
When we last checked, did you load the latest reduced_task3.sql.gz file?

**Comment by mboecker** [comment]
There are 6 runs, which don't have scimark evaluated.
```
+---------+
| rid     |
+---------+
| 7949115 |
| 8297503 |
| 8297504 |
| 8418794 |
| 8529033 |
| 8529303 |
+---------+
6 rows in set (0.28 sec)
```

We can safely ignore these I assume. All other runs have every measure set.

**Comment by mboecker** [comment]
```
+---------+
| rid     |
+---------+
| 2414382 |
| 7949115 |
| 8297503 |
| 8297504 |
| 8418794 |
| 8529033 |
| 8529303 |
+---------+
```

There is only one more run with scimark missing in the full database. We should just ignore scimark on these runs.

**Comment by jakob-r** [comment]
> There are runs without any evaluation measure

I guess this can happen if you upload a configuration but the exection result is not uploaded.
