### ISSUE TITLE
API Call to List all possible Tasks

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#5]
Returns a list of all possible task ids.

**Comment by mboecker** [comment]
Done in 0528bf27ccab7d801d5e8471a4a26af6b881b02d
The API call is /tasks, which will return a list of possible task ids.
Should we add some meta information on the tasks?

**Comment by jakob-r** [comment]
Not necessary for the moment. The user can alway look stuff up on OpenML.
