### ISSUE TITLE
Make sure memoization does not lead to out of memory

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#50]
Currently there is no strategy to delete the cache.

**Comment by mboecker** [comment]
`memA <- memoise(a, ~timeout(10))`

taken from

https://cran.r-project.org/web/packages/memoise/memoise.pdf

this should clear the cache every 10 seconds, but this is not useful when hitting the server with requests about different algos/tasks.

**Comment by jakob-r** [comment]
Yes. This is one disadvantage. The other is that I might want the cache to last longer. But we don't have to put extra effort into that. So Maybe we can stick with something like 30 seconds
