### ISSUE TITLE
Implement normalization for distance check

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#6]
Currently, the SQL query sorts the points in the database by euclidean distance.
But this is suboptimal, if one parameter has a small range, say (0,1), and another parameter has a large range, say (0,1000).
A small change in the second parameter "overrides" any change in parameter one.
Therefore, parameter space should be scaled to a common size.

**Comment by jakob-r** [comment]
Very valid point! 
We have all the necessary information in the parameter descriptions to normalize the values.

My idea would be to scale everything to [0,1]. The problem are [transformations like this](https://github.com/ja-thomas/OMLbots/blob/02f64a48ab45215700ab3c1ef0566c9fc3ac5a74/R/botSetLearnerParamPairs.R#L11). As far as I can see only the transformed part gets stored in the openml database.
The transformation `2^x` means that the e.g. distance between 0 and 1 should be treated equally to the distance between 32 and 64.
I don't see any other way then to manually store the back transformation somewhere and apply it and then do the [0,1] scaling.

**Comment by mboecker** [comment]
TODO
- [ ] save transformations in parameter_ranges
- [ ] when normalizing, check if a transformation is saved in parameter_ranges and apply the function if there is one
- [ ] divide each summand by its scale (either MAX-MIN or parameter_ranges upper-lower) in the sql_generator.R somewhere

**Comment by mboecker** [comment]
The last point is (presumably) already done in FNN. The inverse trafo is still to be added.
