### ISSUE TITLE
Lookup for multiple parameter sets: Factor variables

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#64]
Currently, we subset the table from the database to only contain values, which are identical to the user supplied parameter set (eg. replace = FALSE)

When supplying multiple parameter sets, this approach doesn't work when supplying conflicting data, because we're trying to remove all the runs with replace != FALSE and replace != TRUE.

Do you have an idea for this problem?

**Comment by jakob-r** [comment]
Should be fixed now. Merged also everything to master
