### ISSUE TITLE
No Task Metadata for many tasks

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#89]
```r
task_metadata = readRDS(system.file("docker/omlbotlookup/app/task_metadata.Rds", package = "omlTuneBenchR"))
task.ids = getAvailableTasks()
task.ids[!task.ids %in% task_metadata$task_id]
```

```
 [1]    219    282   6566   7295   9889
 [6]   9910   9914   9946   9952   9957
[11]   9967   9970   9971   9976   9977
[16]   9978   9980   9983  10093  10101
[21]  14951  14952  14965  14966  14971
[26] 125923 145677 145804 145833 145834
[31] 145836 145839 145847 145848 145853
[36] 145854 145855 145857 145862 145872
[41] 145878 145953 145972 145976 145979
[46] 146012 146064 146065 146066 146082
[51] 146085   9911 146803
```

**Comment by jakob-r** [comment]
```
MariaDB [openml_native]> select * from data_quality WHERE data = 219 limit 10;
Empty set (0.00 sec)
```
???

**Comment by jakob-r** [comment]
Okay. It seems like all these datasets where removed from openml :fire: :wastebasket:

**Comment by giuseppec** [comment]
data != task

**Comment by jakob-r** [comment]
Yes. Thanks. I always tend to forget this. :pensive:

**Comment by jakob-r** [comment]
So in table `task_inputs` the value of the input `source_data` links to the dataset id?

**Comment by giuseppec** [comment]
Not sure, I've never looked into the SQL structure of OpenML, maybe @janvanrijn can answer this?
And: Although the OpenML100 has been changed/improved (it's now [OpenML-CC18](https://www.openml.org/s/99)), OpenML usually never removes data sets (it only deactivates them if we recognize that there was something wrong - not sure if deactivating data sets affects the availability of meta information).

**Comment by janvanrijn** [comment]
Datasets can be deleted if there are no tasks associated with it. A task can be deleted if there are no runs associated with it. Tasks that exist should always have metadata. I will not be in office today but feel free to ping me tomorrow or thereafter and i will check what is wrong.

Task creation form on frontend is extremely buggy @joaquinvavschoren when will we disable it?

**Comment by jakob-r** [comment]
@janvanrijn Can you just confirm shortly that the source_data value in `task_inputs` is actually the data set id?

**Comment by janvanrijn** [comment]
Yes. 

If it has a source_data field, and the dataset id is not available, there is a bug, in either the api or task creation form.

**Comment by jakob-r** [comment]
Strangely I am left with three tasks that I can not find metadata for.
These are

```
6566  34536 146085
```
These are linked to these following deactivated dataset:
https://www.openml.org/d/1176

Should we ignore these runs or should we get the task metadata nonetheless? Why is it even missing. The data should be in the DB nonetheless.

**Comment by janvanrijn** [comment]
I now get what you mean with meta data.

This is not part of the immutable definition of openml. In fact, i recently pushed an update that improved the meta feature engine, and recalculated most of these. For this reason you could have missed many. The internet advertisement dataset has an invalid arff definition, i will try to update it with a new version

**Comment by mboecker** [comment]
If we have task metadata on all the tasks, this is resolved.
