### ISSUE TITLE
Task 14966 only has svm runs with kernel=linear

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#90]
Did something went wrong on our side or did the OMLbut not submit anything?

Guess: Any SVM with another kernel then "linear" did not terminate within 21600 seconds (6 hours) because the runtimes from the linear svm are already pretty close to the time out.

**Comment by mboecker** [comment]
```
SELECT DISTINCT implementation.name, input.name, input_setting.value FROM run JOIN input_setting ON input_setting.setup = run.setup JOIN input ON input.id = input_setting.input_id JOIN implementation ON implementation.id = input.implementation_id WHERE run.uploader = 2702 AND task_id = 14966 AND implementation.name = "mlr.classif.svm" AND input.name = "kernel";
```

```
+-----------------+--------+--------+
| name            | name   | value  |
+-----------------+--------+--------+
| mlr.classif.svm | kernel | linear |
+-----------------+--------+--------+
1 row in set (4.44 sec)
```

As you can see, the original database doesn't contain values with another kernel either. Therefore I think your assumption is correct. One way or another the bot didn't insert any runs with a different kernel.
